### ISSUE TITLE
Actualización atributo duracion en una emisora con otra emisora dentro

### ISSUE THREAD

**Issue by nulldiego** [Darktuse/VVS#3]
Cuando se añade una _emisora2_ dentro de una _emisora1_ y luego se añade un contenido a la _emisora2_, no se actualiza el atributo _duracion_ de la _emisora1_.

``` java
Contenido emisora1 = new Emisora("emisora1"); // emisora1
Contenido emisora2 = new Emisora("emisora2"); // emisora2
emisora1.agregar(emisora2, null); // emisora2 en emisora1
Contenido anuncio = new Anuncio(); // nuevo anuncio (duracion = 5)
emisora2.agregar(anuncio, null); // anuncio en emisora2 (y en emisora1)
assertEquals(5, emisora.obtenerDuracion()); // se esperaba 5 pero fue 0
```

Esto se podría corregir calculando la duración en el método _obtenerDuracion_, sumando el _obtenerDuracion_ de cada contenido de la emisora.

**Comment by elenamdf** [comment]
Solucionado!

**Comment by lauramcastro** [comment]
Parabéns a @diegolamas pola súa detallada issue, incluíndo caso de proba! Así se fai.
