### ISSUE TITLE
Atributo de tipo ServidorImplRespaldo en ServidorImplRespaldo.

### ISSUE THREAD

**Issue by ghost** [Darktuse/VVS#4]
¿Por qué el atributo que referencia la idea de servidor de respaldo es de tipo **ServidorImplRespaldo** y no de tipo **Servidor**?

Es más, en el constructor

``` java
public ServidorImplRespaldo(String nombre, Servidor servidorRespaldo) {
    super();
    this.nombre = nombre;
    this.servidorRespaldo = (ServidorImplRespaldo) servidorRespaldo;
}
```

hacéis un cast explícito a **ServidorImplRespaldo**. ¿Qué ocurre si se hace

``` java
new ServidorImplRespaldo("ServidorRespaldo", new ServidorImplSimple("ServidorSimple"));
```

? (Error en tiempo de ejecución, cumplís el interfaz, pero luego forzáis el tipado a una clase hermana, no hija).

Una solución mala podría ser utilizar el operador **instanceof**. La adecuada, declarar el atributo como servidor y así dar más flexibilidad al código.

Otro detalle es permitir null en ese atributo. Si queréis un servidor de respaldo, es para tener al menos un aliado de apoyo. Si no, usa un servidor simple. Supongo.

**Comment by mateof** [comment]
Efectivamente, eso es así. La razón por la cual hemos optado por ese tipo de implementación es el rendimiento y la simplificación.

Por una parte:
- Mejoramos la fácil compartición de tokens entre servidores.

Por otra parte, con lo anterior:
- Nos permite compartir tokens entre el servidor de respaldo y el principal sin tener que crear un nuevo servidor cada vez que se quiera insertar un nuevo token en la nube de servidores.

También favorece el manejo de múltiples tokens por los servidores, su renovación y eliminación.

**Comment by lauramcastro** [comment]
Non estou dacordo coa clasificación desta issue como inválida. Todos os argumentos de @manoelfolgueira son válidos. Porén, de entre os argumentos de @mateof o rendemento non está demostrado que se sexa mellor (onde está a proba non funcional que o mostra?); en canto á simplicidade da implementación, é unha característica a ter en conta, pero nunca debe sacrificar o chamado principio de mínima sorpresa (se un ServidorRespaldo acepta calquera Servidor e eu paso un implementado por min, non debería romperse todo).

Que os tokens sexan compartidos entre servidores é unha decisión vosa, posterior á especificación. Estades sacrificando aspectos que derivan da especificación para favorecer unha decisión de implementación vosa. Non se xustifica.

Porén, esta issue é válida e debería ser tratada como bug.
