### ISSUE TITLE
Servidor de Respaldo del tipo Servidor Simple

### ISSUE THREAD

**Issue by eabanqueiro** [Darktuse/VVS#5]
Cada servidor puede tener un servidor de respaldo asociado,  para hacer una cadena de servidores todos tienen que ser del tipo ServidorRespaldo excepto el último que podría ser de tipo ServidorRespaldo o ServidorSimple. En vuestro caso no deja que el ultimo servidor sea un ServidorSimple. Es decir, no deja hacer lo siguiente:

```
    Servidor servidorSimple = new ServidorImplSimple("s2");
    servidorSimple.agregar(new Cancion("cancion 1", 5), tokenSpecial);
    servidorSimple.agregar(new Cancion("cancion 2", 3), tokenSpecial);
    ServidorImplSimple respaldo = (ServidorImplSimple) servidorSimple;
    ServidorImplRespaldo servidor = (ServidorImplRespaldo) servidorValidvacioConRespaldo(respaldo);

    String t = servidor.alta();
    assertEquals(servidor.buscar("cancion 2", t).size(),1);
```

**Comment by lauramcastro** [comment]
Efectivamente, esta issue é duplicada de #4 , podedes por tanto pechala ademáis de etiquetala.t
