### ISSUE TITLE
Estructuración

### ISSUE THREAD

**Issue by galu8** [Darktuse/VVS#6]
Según lo mencionado en clase de Teoría, el diseño y estructura de la práctica también se valora. Por lo tanto lo óptimo sería estructurar en paquetes las clases y no meter todo en el mismo.
Además, creemos que, para no duplicar métodos idénticos(por ejemplo el obtenerNombre ,las funciones auxiliares,...) se debería crear una clase abstracta de servidor que implemente  la interfaz, y que servidor simple y de respaldo extiendan de esa clase abstracta(Si vais al uml de nuestra documentación podréis ver a lo que me refiero en caso de duda).

**Comment by elenamdf** [comment]
Corregida la estructura de la práctica (añadidos los paquetes de Contenido y de Servidor).

**Comment by lauramcastro** [comment]
Se xa solucionastes todos os aspectos indicados por @galu8 entón pechade a issue, non a marquedes como inválida :-?
